const BREEDS_URL = "https://dog.ceo/api/breeds/list/all";

const select = document.querySelector(".breeds");

fetch(BREEDS_URL)
  .then((res) => {
    return res.json();
  })
  .then((data) => {
    const breedsObject = data.message; //Turn the message into an object
    const breedsArray = Object.keys(breedsObject); //Turn the object into an array
    for (i = 0; i < breedsArray.length; i++) {
      const option = document.createElement("option");
      option.value = breedsArray[i];
      option.innerText = breedsArray[i];
      select.appendChild(option);
    }
  });

select.addEventListener("change", (event) => {
  let url = `https://dog.ceo/api/breed/${event.target.value}/images/random`;
  getDoggoImg(url);
  doggieInfo.assignMF();
  doggieInfo.assignAge();
  doggieInfo.assignLikes();
  doggieInfo.assignDislikes();
  doggieInfo.assignFunFact();
});

const img = document.querySelector(".dog-img");

const getDoggoImg = (url) => {
  fetch(url) //going to the API URL above
    .then((res) => {
      return res.json(); //gte json message back
    })
    .then((data) => {
      img.src = data.message; //extract message from json and attach to image tag as new source
    });
};

const doggieInfo = {
  fNames: [
    "Abby",
    "Addie",
    "Alexis",
    "Alice",
    "Allie",
    "Alyssa",
    "Amber",
    "Angel",
    "Anna",
    "Annie",
    "Ariel",
    "Ashley",
    "Athena",
    "Autumn",
    "Ava",
    "Aries",
    "Baby",
    "Baby",
    "Bailey",
    "Basil",
    "Bean",
    "Bella",
    "Belle",
    "Betsy",
    "Betty",
    "Bianca",
    "Birdie",
    "Biscuit",
    "Blondie",
    "Blossom",
    "Bonnie",
    "Brandy",
    "Brooklyn",
    "Brownie",
    "Buffy",
    "Callie",
    "Camilla",
    "Candy",
    "Carla",
    "Carly",
    "Carmela",
    "Casey",
    "Cassie",
    "Chance",
    "Chanel",
    "Chloe",
    "Cleo",
    "Cinnamon",
    "Coco",
    "Cookie",
    "Cricket",
    "Daisy",
    "Dakota",
    "Dana",
    "Daphne",
    "Darla",
    "Darlene",
    "Delia",
    "Delilah",
    "Destiny",
    "Diamond",
    "Diva",
    "Dixie",
    "Dolly",
    "Duchess",
    "Eden",
    "Edie",
    "Ella",
    "Ellie",
    "Elsa",
    "Emma",
    "Emmy",
    "Eva",
    "Faith",
    "Fanny",
    "Fern",
    "Fiona",
    "Foxy",
    "Gabby",
    "Gemma",
    "Georgia",
    "Gia",
    "Gidget",
    "Gigi",
    "Ginger",
    "Goldie",
    "Grace",
    "Gracie",
    "Greta",
    "Gypsy",
    "Hailey",
    "Hannah",
    "Harley",
    "Harper",
    "Hazel",
    "Heidi",
    "Hershey",
    "Holly",
    "Honey",
    "Hope",
    "Ibby",
    "Inez",
    "Isabella",
    "Ivy",
    "Izzy",
    "Jackie",
    "Jada",
    "Jade",
    "Jasmine",
    "Jenna",
    "Jersey",
    "Jessie",
    "Jill",
    "Josie",
    "Julia",
    "Juliet",
    "Juno",
    "Kali",
    "Kallie",
    "Karma",
    "Kate",
    "Katie",
    "Kayla",
    "Kelsey",
    "Khloe",
    "Kiki",
    "Kira",
    "Koko",
    "Kona",
    "Lacey",
    "Lady",
    "Layla",
    "Leia",
    "Lena",
    "Lexi",
    "Libby",
    "Liberty",
    "Lily",
    "Lizzy",
    "Lola",
    "London",
    "Lucky",
    "Lulu",
    "Luna",
    "Mabel",
    "Mackenzie",
    "Maddie",
    "Madison",
    "Maggie",
    "Maisy",
    "Mandy",
    "Marley",
    "Matilda",
    "Mattie",
    "Maya",
    "Mia",
    "Mika",
    "Mila",
    "Miley",
    "Millie",
    "Mimi",
    "Minnie",
    "Missy",
    "Misty",
    "Mitzi",
    "Mocha",
    "Molly",
    "Morgan",
    "Moxie",
    "Muffin",
    "Mya",
    "Nala",
    "Nell",
    "Nellie",
    "Nikki",
    "Nina",
    "Noel",
    "Nola",
    "Nori",
    "Olive",
    "Olivia",
    "Oreo",
    "Paisley",
    "Pandora",
    "Paris",
    "Peaches",
    "Peanut",
    "Pearl",
    "Pebbles",
    "Penny",
    "Pepper",
    "Phoebe",
    "Piper",
    "Pippa",
    "Pixie",
    "Polly",
    "Poppy",
    "Precious",
    "Princess",
    "Priscilla",
    "Raven",
    "Reese",
    "Riley",
    "Rose",
    "Rosie",
    "Roxy",
    "Ruby",
    "Sadie",
    "Sage",
    "Sally",
    "Sam",
    "Samantha",
    "Sammie",
    "Sandy",
    "Sasha",
    "Sassy",
    "Savannah",
    "Scarlet",
    "Shadow",
    "Sheba",
    "Shelby",
    "Shiloh",
    "Sierra",
    "Sissy",
    "Sky",
    "Smokey",
    "Snickers",
    "Sophia",
    "Sophie",
    "Star",
    "Stella",
    "Sugar",
    "Suki",
    "Summer",
    "Sunny",
    "Sweetie",
    "Sydney",
    "Tasha",
    "Tessa",
    "Tilly",
    "Tootsie",
    "Trixie",
    "Violet",
    "Willow",
    "Winnie",
    "Xena",
    "Zelda",
    "Zoe",
  ],
  mNames: [
    "Abe",
    "Abbott",
    "Ace",
    "Aero",
    "Aiden",
    "AJ",
    "Albert",
    "Alden",
    "Alex",
    "Alfie",
    "Alvin",
    "Amos",
    "Aspen",
    "Andy",
    "Angus",
    "Apollo",
    "Archie",
    "Avery",
    "Artie",
    "Ash",
    "Austin",
    "Axel",
    "Bailey",
    "Bandit",
    "Barkley",
    "Barney",
    "Baron",
    "Baxter",
    "Bear",
    "Beau",
    "Benji",
    "Benny",
    "Bentley",
    "Billy",
    "Bingo",
    "Blake",
    "Blaze",
    "Blue",
    "Bo",
    "Boomer",
    "Brady",
    "Brody",
    "Brownie",
    "Bruce",
    "Bruno",
    "Brutus",
    "Bubba",
    "Buck",
    "Buddy",
    "Buster",
    "Butch",
    "Buzz",
    "Cain",
    "Captain",
    "Carter",
    "Cash",
    "Casper",
    "Champ",
    "Chance",
    "Charlie",
    "Chase",
    "Chester",
    "Chewy",
    "Chico",
    "Chief",
    "Chip",
    "CJ",
    "Clifford",
    "Clyde",
    "Coco",
    "Cody",
    "Colby",
    "Cooper",
    "Copper",
    "Damien",
    "Dane",
    "Dante",
    "Denver",
    "Dexter",
    "Diego",
    "Diesel",
    "Dodge",
    "Drew",
    "Duke",
    "Dylan",
    "Eddie",
    "Eli",
    "Elmer",
    "Emmett",
    "Evan",
    "Felix",
    "Finn",
    "Fisher",
    "Flash",
    "Frankie",
    "Freddy",
    "Fritz",
    "Gage",
    "George",
    "Gizmo",
    "Goose",
    "Gordie",
    "Griffin",
    "Gunner",
    "Gus",
    "Hank",
    "Harley",
    "Harvey",
    "Hawkeye",
    "Henry",
    "Hoss",
    "Huck",
    "Hunter",
    "Iggy",
    "Ivan",
    "Jack",
    "Jackson",
    "Jake",
    "Jasper",
    "Jax",
    "Jesse",
    "Joey",
    "Johnny",
    "Judge",
    "Kane",
    "King",
    "Kobe",
    "Koda",
    "Lenny",
    "Leo",
    "Leroy",
    "Levi",
    "Lewis",
    "Logan",
    "Loki",
    "Louie",
    "Lucky",
    "Luke",
    "Marley",
    "Marty",
    "Maverick",
    "Max",
    "Maximus",
    "Mickey",
    "Miles",
    "Milo",
    "Moe",
    "Moose",
    "Morris",
    "Murphy",
    "Ned",
    "Nelson",
    "Nero",
    "Nico",
    "Noah",
    "Norm",
    "Oakley",
    "Odie",
    "Odin",
    "Oliver",
    "Ollie",
    "Oreo",
    "Oscar",
    "Otis",
    "Otto",
    "Ozzy",
    "Pablo",
    "Parker",
    "Peanut",
    "Pepper",
    "Petey",
    "Porter",
    "Prince",
    "Quincy",
    "Radar",
    "Ralph",
    "Rambo",
    "Ranger",
    "Rascal",
    "Rebel",
    "Reese",
    "Reggie",
    "Remy",
    "Rex",
    "Ricky",
    "Rider",
    "Riley",
    "Ringo",
    "Rocco",
    "Rockwell",
    "Rocky",
    "Romeo",
    "Rosco",
    "Rudy",
    "Rufus",
    "Rusty",
    "Sam",
    "Sammy",
    "Samson",
    "Sarge",
    "Sawyer",
    "Scooby",
    "Scooter",
    "Scout",
    "Scrappy",
    "Shadow",
    "Shamus",
    "Shiloh",
    "Simba",
    "Simon",
    "Smoky",
    "Snoopy",
    "Sparky",
    "Spencer",
    "Spike",
    "Spot",
    "Stanley",
    "Stewie",
    "Storm",
    "Taco",
    "Tank",
    "Taz",
    "Teddy",
    "Tesla",
    "Theo",
    "Thor",
    "Titus",
    "TJ",
    "Toby",
    "Trapper",
    "Tripp",
    "Tucker",
    "Tyler",
    "Tyson",
    "Vince",
    "Vinnie",
    "Wally",
    "Walter",
    "Watson",
    "Willy",
    "Winston",
    "Woody",
    "Wrigley",
    "Wyatt",
    "Yogi",
    "Yoshi",
    "Yukon",
    "Zane",
    "Zeus",
    "Ziggy",
  ],
  likesList: [
    "Eating with others",
    "having friends",
    "Pets",
    "Scratches under the chin",
    "Scratches behind the ears",
    "Chasing squirrels",
    "Chasing cars",
    "Fetching the ball",
    "Napping",
    "Ice water from McDonalds",
    "Rides to the park",
    "Rides to Starbucks for a Puppaccinno",
    "Staring out the window",
    "Wind in their fur",
    "Eating pillows",
  ],

  dislikesList: [
    "Eating alone",
    "Doorbells",
    "Not being allowed to nap",
    "Roombas",
    "Small children",
    "Thunder",
    "Staying clean after a bath",
    "Loud water",
    "Baths",
    "Soap",
    "Being caught in the trash",
  ],

  factList: [
    "Remembers every squirrel they have ever chased",
    "Wants to go back to that one spot they found cheese on a walk",
    "Knows the quantum theory, just cannot express it",
    "would be a professional violinist if they had thumbs",
    "Wishes they knew how cars worked",
    "Constantly asks if we can all just get along but then gets distracted by-OOoo, shiney!",
    "Understands more words then we give them credit for",
    "Wants whatever you're eating, no matter what",
  ],
  MF: "",
  rname: "",
  age: "",
  likes: "",
  dislikes: "",
  fact: "",

  assignMF() {
    x = Math.floor(Math.random() * 2) == 0;
    if (x) {
      this.MF = "Female";
      this.assignName(this.fNames);
    } else {
      this.MF = "Male";
      this.assignName(this.mNames);
    }
    document.getElementById("MF").innerHTML = `S: ${this.MF}`;
  },
  assignName(array) {
    this.rname = array[Math.floor(Math.random() * array.length)];
    document.getElementById("dog-name").innerHTML = `${this.rname}`;
  },

  assignAge() {
    this.age = Math.floor(Math.random() * 16 + 1);
    document.getElementById("age").innerHTML = `Age: ${this.age}`;
  },

  yatesShuffle(array) {
    let m = array.length,
      t,
      i;
    while (m) {
      i = Math.floor(Math.random() * m--);
      t = array[m];
      array[m] = array[i];
      array[i] = t;
    }
    return array;
  },

  assignLikes() {
    this.likes = this.yatesShuffle(this.likesList).slice(0, 2);
    document.getElementById("likes").innerHTML = `Likes: ${
      (this.likes[0], this.likes[1])
    }`;
  },

  assignDislikes() {
    this.dislikes = this.yatesShuffle(this.dislikesList).slice(0, 2);
    document.getElementById("dislikes").innerHTML = `Dislikes: ${
      (this.dislikes[0], this.dislikes[1])
    }`;
  },

  assignFunFact() {
    this.fact = this.factList[Math.floor(Math.random() * this.factList.length)];
    document.getElementById("fun-fact").innerHTML = `Fun Fact: ${this.fact}`;
  },
};
